#!/bin/bash
# This is a simple post deploy hook executed after your application
# is deployed and started.  This script gets executed directly, so
# it could be python, php, ruby, etc.

echo "--> ACTION HOOK: post_deploy <--"

#echo "Executing 'mongorestore --db skool $OPENSHIFT_REPO_DIR../../data/dbdata/dump/'"
#cd na spravne misto
#mongorestore --host "$OPENSHIFT_MONGODB_DB_HOST":"$OPENSHIFT_MONGODB_DB_PORT" --username admin --password NjAjjd2L76A-
